//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomobilePurchaseOrder.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartDetails", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PartDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartID {
            get {
                return this.PartIDField;
            }
            set {
                if ((this.PartIDField.Equals(value) != true)) {
                    this.PartIDField = value;
                    this.RaisePropertyChanged("PartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartName {
            get {
                return this.PartNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNameField, value) != true)) {
                    this.PartNameField = value;
                    this.RaisePropertyChanged("PartName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MfgDetails", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MfgDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MfgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MfgID {
            get {
                return this.MfgIDField;
            }
            set {
                if ((this.MfgIDField.Equals(value) != true)) {
                    this.MfgIDField = value;
                    this.RaisePropertyChanged("MfgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgName {
            get {
                return this.OrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgNameField, value) != true)) {
                    this.OrgNameField = value;
                    this.RaisePropertyChanged("OrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartName {
            get {
                return this.PartNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNameField, value) != true)) {
                    this.PartNameField = value;
                    this.RaisePropertyChanged("PartName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertPartDetails", ReplyAction="http://tempuri.org/IService/InsertPartDetailsResponse")]
        void InsertPartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectPartDetails", ReplyAction="http://tempuri.org/IService/SelectPartDetailsResponse")]
        System.Data.DataSet SelectPartDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePartDetails", ReplyAction="http://tempuri.org/IService/DeletePartDetailsResponse")]
        void DeletePartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdatePartDetails", ReplyAction="http://tempuri.org/IService/UpdatePartDetailsResponse")]
        void UpdatePartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertMfgDetails", ReplyAction="http://tempuri.org/IService/InsertMfgDetailsResponse")]
        void InsertMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectMfgDetails", ReplyAction="http://tempuri.org/IService/SelectMfgDetailsResponse")]
        System.Data.DataSet SelectMfgDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMfgDetails", ReplyAction="http://tempuri.org/IService/DeleteMfgDetailsResponse")]
        void DeleteMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateMfgDetails", ReplyAction="http://tempuri.org/IService/UpdateMfgDetailsResponse")]
        void UpdateMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/QueryCarPart", ReplyAction="http://tempuri.org/IService/QueryCarPartResponse")]
        System.Data.DataSet QueryCarPart(string parts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SerializeCarParts", ReplyAction="http://tempuri.org/IService/SerializeCarPartsResponse")]
        string SerializeCarParts(string parts);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceChannel : AutomobilePurchaseOrder.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AutomobilePurchaseOrder.ServiceReference1.IService>, AutomobilePurchaseOrder.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertPartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo) {
            base.Channel.InsertPartDetails(partInfo);
        }
        
        public System.Data.DataSet SelectPartDetails() {
            return base.Channel.SelectPartDetails();
        }
        
        public void DeletePartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo) {
            base.Channel.DeletePartDetails(partInfo);
        }
        
        public void UpdatePartDetails(AutomobilePurchaseOrder.ServiceReference1.PartDetails partInfo) {
            base.Channel.UpdatePartDetails(partInfo);
        }
        
        public void InsertMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo) {
            base.Channel.InsertMfgDetails(mfgInfo);
        }
        
        public System.Data.DataSet SelectMfgDetails() {
            return base.Channel.SelectMfgDetails();
        }
        
        public void DeleteMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo) {
            base.Channel.DeleteMfgDetails(mfgInfo);
        }
        
        public void UpdateMfgDetails(AutomobilePurchaseOrder.ServiceReference1.MfgDetails mfgInfo) {
            base.Channel.UpdateMfgDetails(mfgInfo);
        }
        
        public System.Data.DataSet QueryCarPart(string parts) {
            return base.Channel.QueryCarPart(parts);
        }
        
        public string SerializeCarParts(string parts) {
            return base.Channel.SerializeCarParts(parts);
        }
    }
}
